[package]
name = "metabolomics-datasets-rs"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
zenodo-rs = { version = "0.3.0", features = ["checksums", "indicatif"] }

[lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
nursery = { level = "warn", priority = -1 }
missing_docs_in_private_items = "deny"
missing_errors_doc = "deny"
missing_panics_doc = "deny"
missing_safety_doc = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
undocumented_unsafe_blocks = "deny"
multiple_crate_versions = "deny"